### ISSUE TITLE
SSL Service available on PWS?

### ISSUE THREAD

**Issue by wgu** [pivotal-cf/docs-pws-services#16]
It looks like we are having a page for SSL service about a month ago and it is reflecting on the public PWS docs but it seems not actually available on PWS? 

Docs: http://docs.run.pivotal.io/marketplace/pivotal-ssl.html
https://github.com/pivotal-cf/docs-pws-services/blob/master/pivotal-ssl.html.md.erb

Zendesk ticket: https://discuss.zendesk.com/agent/tickets/15420

**Comment by animatedmax** [comment]
Charles decided on adding a note to the top of the pivotal-ssl topic explaining it is available to PCF customers using PWS:
http://docs-runpivotal-acceptance.cfapps.io/marketplace/pivotal-ssl.html
