### ISSUE TITLE
Is mLab still supported from Pivotal Marketplace free trial plan?

### ISSUE THREAD

**Issue by davidljuba15031979** [pivotal-cf/docs-pws-services#35]
According to docs it seams that mLab is supported by Pivotal: 

https://docs.run.pivotal.io/marketplace/services/mlab.html
https://github.com/pivotal-cf/docs-pws-services/blob/master/services/mlab.html.md.erb

In list of Marketplace services is not shown:

![MarketplaceWithoutMLab](https://user-images.githubusercontent.com/37576531/95723649-a9898100-0c75-11eb-922a-fc566d54062c.png)

Is this related to Pivotal trial payment plan?

Thanks,
David

**Comment by mlimonczenko** [comment]
Hello @davidljuba15031979,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
